// Copyright 2026 The Monti Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/monti/socks_bridge.h"

#include <algorithm>
#include <cstdint>
#include <set>
#include <string>
#include <utility>
#include <vector>

#include "base/base64.h"
#include "base/containers/span.h"
#include "base/containers/unique_ptr_adapters.h"
#include "base/functional/bind.h"
#include "base/functional/callback_helpers.h"
#include "base/location.h"
#include "base/logging.h"
#include "base/memory/raw_ptr.h"
#include "base/memory/scoped_refptr.h"
#include "base/memory/weak_ptr.h"
#include "base/strings/strcat.h"
#include "base/strings/string_number_conversions.h"
#include "base/task/sequenced_task_runner.h"
#include "net/base/address_list.h"
#include "net/base/io_buffer.h"
#include "net/base/ip_address.h"
#include "net/base/ip_endpoint.h"
#include "net/base/net_errors.h"
#include "net/log/net_log.h"
#include "net/log/net_log_source.h"
#include "net/socket/stream_socket.h"
#include "net/socket/tcp_client_socket.h"
#include "net/socket/tcp_server_socket.h"
#include "net/traffic_annotation/network_traffic_annotation.h"

namespace monti {

namespace {

// SOCKS5 protocol constants.
constexpr uint8_t kSocks5Version = 0x05;
constexpr uint8_t kAuthNone = 0x00;
constexpr uint8_t kAuthUserPass = 0x02;
constexpr uint8_t kRfc1929Version = 0x01;
constexpr uint8_t kAtypIPv4 = 0x01;
constexpr uint8_t kAtypDomain = 0x03;
constexpr uint8_t kAtypIPv6 = 0x04;
constexpr uint8_t kCmdConnect = 0x01;

// Scratch buffer big enough for any single SOCKS5 handshake read (the largest
// is a domain address: 1 length byte + 255 + 2 port bytes).
constexpr int kHandshakeScratchSize = 512;
// Relay buffer per direction.
constexpr int kRelayCapacity = 32 * 1024;

constexpr net::NetworkTrafficAnnotationTag kTrafficAnnotation =
    net::DefineNetworkTrafficAnnotation("monti_socks_bridge", R"(
        semantics {
          sender: "Monti SOCKS5 Bridge"
          description:
            "Monti runs a localhost forwarder so the browser can use SOCKS5 "
            "proxies that require username/password authentication. The browser "
            "connects to 127.0.0.1 without auth; this forwarder relays the bytes "
            "to the user-configured upstream proxy, performing RFC 1929 "
            "authentication on the upstream leg."
          trigger:
            "The user connects a profile to an authenticated SOCKS5 proxy via "
            "the Monti side panel."
          data:
            "Arbitrary TCP traffic generated by the browsing session, plus the "
            "proxy credentials entered by the user (sent only to the upstream "
            "proxy the user configured)."
          destination: OTHER
          destination_other: "The SOCKS5 proxy server configured by the user."
        }
        policy {
          cookies_allowed: NO
          setting: "This forwarder only runs while a profile is connected to a "
                   "SOCKS5 proxy in the Monti side panel."
          policy_exception_justification: "Not implemented; Monti-specific."
        })");

std::vector<uint8_t> StringToBytes(const std::string& value) {
  return std::vector<uint8_t>(value.begin(), value.end());
}

uint16_t ReadBigEndianPort(base::span<const uint8_t> bytes) {
  return (static_cast<uint16_t>(bytes[0]) << 8) | bytes[1];
}

}  // namespace

// A single accepted local connection: drives the SOCKS5 handshake on both legs,
// then relays bytes transparently. Owned (via unique_ptr) by its BridgeInstance;
// on any error it asks the owner to delete it, which closes both sockets.
class SocksBridge::BridgeConnection {
 public:
  BridgeConnection(BridgeInstance* owner,
                   std::unique_ptr<net::StreamSocket> local,
                   const MontiProxy& proxy)
      : owner_(owner),
        proxy_(proxy),
        local_(std::move(local)),
        scratch_(base::MakeRefCounted<net::IOBufferWithSize>(
            kHandshakeScratchSize)) {}

  BridgeConnection(const BridgeConnection&) = delete;
  BridgeConnection& operator=(const BridgeConnection&) = delete;
  ~BridgeConnection() = default;

  // Begins by reading the local client's SOCKS5 greeting.
  void Start() {
    ReadN(local_.get(), 2,
          base::BindOnce(&BridgeConnection::OnLocalGreetHeader,
                         base::Unretained(this)));
  }

 private:
  // --- Generic helpers --------------------------------------------------

  // Reads exactly `n` bytes from `s` into rbuf_, then runs `done`.
  void ReadN(net::StreamSocket* s, size_t n, base::OnceClosure done) {
    rbuf_.clear();
    rbuf_need_ = n;
    read_socket_ = s;
    read_done_ = std::move(done);
    if (n == 0) {
      std::move(read_done_).Run();
      return;
    }
    DoRead();
  }

  void DoRead() {
    const size_t remaining = rbuf_need_ - rbuf_.size();
    const int want = static_cast<int>(
        std::min(remaining, static_cast<size_t>(scratch_->size())));
    int rv = read_socket_->Read(
        scratch_.get(), want,
        base::BindOnce(&BridgeConnection::OnRead, base::Unretained(this)));
    if (rv != net::ERR_IO_PENDING) {
      OnRead(rv);
    }
  }

  void OnRead(int rv) {
    if (rv <= 0) {
      Fail();
      return;
    }
    const base::span<const uint8_t> chunk =
        scratch_->span().first(static_cast<size_t>(rv));
    rbuf_.insert(rbuf_.end(), chunk.begin(), chunk.end());
    if (rbuf_.size() < rbuf_need_) {
      DoRead();
      return;
    }
    std::move(read_done_).Run();
  }

  // Writes all of `data` to `s`, then runs `done`.
  void WriteAll(net::StreamSocket* s,
                std::vector<uint8_t> data,
                base::OnceClosure done) {
    auto vec = base::MakeRefCounted<net::VectorIOBuffer>(std::move(data));
    const int total = vec->size();
    write_drain_ =
        base::MakeRefCounted<net::DrainableIOBuffer>(std::move(vec), total);
    write_socket_ = s;
    write_done_ = std::move(done);
    if (total == 0) {
      std::move(write_done_).Run();
      return;
    }
    DoWrite();
  }

  void DoWrite() {
    int rv = write_socket_->Write(
        write_drain_.get(), write_drain_->BytesRemaining(),
        base::BindOnce(&BridgeConnection::OnWrite, base::Unretained(this)),
        kTrafficAnnotation);
    if (rv != net::ERR_IO_PENDING) {
      OnWrite(rv);
    }
  }

  void OnWrite(int rv) {
    if (rv <= 0) {
      Fail();
      return;
    }
    write_drain_->DidConsume(rv);
    if (write_drain_->BytesRemaining() > 0) {
      DoWrite();
      return;
    }
    std::move(write_done_).Run();
  }

  // --- Local (browser-facing) SOCKS5 handshake: no auth -----------------

  void OnLocalGreetHeader() {
    if (rbuf_[0] != kSocks5Version) {
      Fail();
      return;
    }
    const size_t nmethods = rbuf_[1];
    ReadN(local_.get(), nmethods,
          base::BindOnce(&BridgeConnection::OnLocalGreetMethods,
                         base::Unretained(this)));
  }

  void OnLocalGreetMethods() {
    // Select "no authentication" for the local leg.
    WriteAll(local_.get(), {kSocks5Version, kAuthNone},
             base::BindOnce(&BridgeConnection::OnLocalGreetReplied,
                            base::Unretained(this)));
  }

  void OnLocalGreetReplied() {
    // Read the request header: VER CMD RSV ATYP.
    ReadN(local_.get(), 4,
          base::BindOnce(&BridgeConnection::OnLocalRequestHeader,
                         base::Unretained(this)));
  }

  void OnLocalRequestHeader() {
    if (rbuf_[0] != kSocks5Version || rbuf_[1] != kCmdConnect) {
      Fail();
      return;
    }
    // Preserve the request verbatim; it is replayed to the upstream proxy.
    request_.assign(rbuf_.begin(), rbuf_.end());
    const uint8_t atyp = rbuf_[3];
    if (atyp == kAtypIPv4) {
      ReadN(local_.get(), 4 + 2,
            base::BindOnce(&BridgeConnection::OnLocalRequestAddr,
                           base::Unretained(this)));
    } else if (atyp == kAtypIPv6) {
      ReadN(local_.get(), 16 + 2,
            base::BindOnce(&BridgeConnection::OnLocalRequestAddr,
                           base::Unretained(this)));
    } else if (atyp == kAtypDomain) {
      ReadN(local_.get(), 1,
            base::BindOnce(&BridgeConnection::OnLocalRequestDomainLen,
                           base::Unretained(this)));
    } else {
      Fail();
    }
  }

  void OnLocalRequestDomainLen() {
    request_.push_back(rbuf_[0]);
    const size_t domain_len = rbuf_[0];
    ReadN(local_.get(), domain_len + 2,
          base::BindOnce(&BridgeConnection::OnLocalRequestAddr,
                         base::Unretained(this)));
  }

  void OnLocalRequestAddr() {
    request_.insert(request_.end(), rbuf_.begin(), rbuf_.end());
    if (!ParseLocalRequestTarget()) {
      Fail();
      return;
    }
    ConnectUpstream();
  }

  bool ParseLocalRequestTarget() {
    if (request_.size() < 7) {
      return false;
    }
    const uint8_t atyp = request_[3];
    size_t port_offset = 0;
    if (atyp == kAtypIPv4) {
      if (request_.size() != 10) {
        return false;
      }
      net::IPAddress ip(base::span(request_).subspan<4u, 4u>());
      target_host_ = ip.ToString();
      port_offset = 8;
    } else if (atyp == kAtypIPv6) {
      if (request_.size() != 22) {
        return false;
      }
      net::IPAddress ip(base::span(request_).subspan<4u, 16u>());
      target_host_ = ip.ToString();
      port_offset = 20;
    } else if (atyp == kAtypDomain) {
      const size_t domain_len = request_[4];
      if (request_.size() != 4 + 1 + domain_len + 2) {
        return false;
      }
      target_host_.assign(reinterpret_cast<const char*>(&request_[5]),
                          domain_len);
      port_offset = 5 + domain_len;
    } else {
      return false;
    }
    target_port_ =
        ReadBigEndianPort(base::span(request_).subspan(port_offset, 2u));
    return !target_host_.empty() && target_port_ > 0;
  }

  // --- Upstream (proxy-facing) SOCKS5 handshake: RFC 1929 auth ----------

  void ConnectUpstream() {
    net::IPAddress ip;
    // MVP: upstream host must be an IP literal (matches the CSV proxy format).
    if (!ip.AssignFromIPLiteral(proxy_.host)) {
      VLOG(1) << "Monti SOCKS bridge: upstream host is not an IP literal: "
              << proxy_.host;
      Fail();
      return;
    }
    upstream_ = std::make_unique<net::TCPClientSocket>(
        net::AddressList::CreateFromIPAddress(
            ip, static_cast<uint16_t>(UpstreamPort())),
        /*socket_performance_watcher=*/nullptr,
        /*network_quality_estimator=*/nullptr, /*net_log=*/nullptr,
        net::NetLogSource());
    int rv = upstream_->Connect(base::BindOnce(
        &BridgeConnection::OnUpstreamConnected, base::Unretained(this)));
    if (rv != net::ERR_IO_PENDING) {
      OnUpstreamConnected(rv);
    }
  }

  void OnUpstreamConnected(int rv) {
    if (rv != net::OK) {
      if (MaybeRetryHttpEndpointAsSocks()) {
        return;
      }
      Fail();
      return;
    }
    if (proxy_.transport == "http" && !force_socks_upstream_) {
      SendHttpConnect();
      return;
    }
    // Offer username/password auth.
    WriteAll(upstream_.get(), {kSocks5Version, 0x01, kAuthUserPass},
             base::BindOnce(&BridgeConnection::OnUpstreamGreetSent,
                            base::Unretained(this)));
  }

  int UpstreamPort() const {
    if (proxy_.transport == "http") {
      return proxy_.http_port;
    }
    return proxy_.socks_port;
  }

  bool MaybeRetryHttpEndpointAsSocks() {
    if (proxy_.transport != "http" || force_socks_upstream_) {
      return false;
    }
    force_socks_upstream_ = true;
    upstream_.reset();
    ConnectUpstream();
    return true;
  }

  std::string TargetHostForHttpHeader() const {
    return target_host_.find(':') == std::string::npos
               ? target_host_
               : base::StrCat({"[", target_host_, "]"});
  }

  void SendHttpConnect() {
    const std::string target = base::StrCat(
        {TargetHostForHttpHeader(), ":", base::NumberToString(target_port_)});
    std::string request =
        base::StrCat({"CONNECT ", target, " HTTP/1.1\r\n",
                      "Host: ", target, "\r\n",
                      "Proxy-Connection: keep-alive\r\n"});
    if (!proxy_.username.empty() || !proxy_.password.empty()) {
      request = base::StrCat(
          {request, "Proxy-Authorization: Basic ",
           base::Base64Encode(
               base::StrCat({proxy_.username, ":", proxy_.password})),
           "\r\n"});
    }
    request.append("\r\n");
    WriteAll(upstream_.get(), StringToBytes(request),
             base::BindOnce(&BridgeConnection::OnHttpConnectSent,
                            base::Unretained(this)));
  }

  void OnHttpConnectSent() {
    http_response_.clear();
    ReadHttpConnectResponse();
  }

  void ReadHttpConnectResponse() {
    int rv = upstream_->Read(
        scratch_.get(), scratch_->size(),
        base::BindOnce(&BridgeConnection::OnHttpConnectRead,
                       base::Unretained(this)));
    if (rv != net::ERR_IO_PENDING) {
      OnHttpConnectRead(rv);
    }
  }

  void OnHttpConnectRead(int rv) {
    if (rv <= 0) {
      if (MaybeRetryHttpEndpointAsSocks()) {
        return;
      }
      Fail();
      return;
    }
    const base::span<const uint8_t> chunk =
        scratch_->span().first(static_cast<size_t>(rv));
    http_response_.append(reinterpret_cast<const char*>(chunk.data()),
                          chunk.size());
    if (http_response_.size() > kRelayCapacity) {
      Fail();
      return;
    }
    if (http_response_.find("\r\n\r\n") == std::string::npos) {
      ReadHttpConnectResponse();
      return;
    }
    const int status = ParseHttpConnectStatus();
    if (status < 200 || status > 299) {
      VLOG(1) << "Monti proxy bridge: upstream HTTP CONNECT failed with "
              << status;
      if (MaybeRetryHttpEndpointAsSocks()) {
        return;
      }
      Fail();
      return;
    }
    // The browser-facing side is SOCKS5, so synthesize a successful SOCKS5
    // CONNECT reply once the upstream HTTP tunnel is established.
    WriteAll(local_.get(), {kSocks5Version, 0x00, 0x00, kAtypIPv4,
                            0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
             base::BindOnce(&BridgeConnection::OnLocalReplySent,
                            base::Unretained(this)));
  }

  int ParseHttpConnectStatus() const {
    if (!http_response_.starts_with("HTTP/")) {
      return 0;
    }
    const size_t first_space = http_response_.find(' ');
    if (first_space == std::string::npos ||
        first_space + 4 > http_response_.size()) {
      return 0;
    }
    int status = 0;
    if (!base::StringToInt(http_response_.substr(first_space + 1, 3),
                           &status)) {
      return 0;
    }
    return status;
  }

  void OnUpstreamGreetSent() {
    ReadN(upstream_.get(), 2,
          base::BindOnce(&BridgeConnection::OnUpstreamGreetReply,
                         base::Unretained(this)));
  }

  void OnUpstreamGreetReply() {
    if (rbuf_[0] != kSocks5Version) {
      Fail();
      return;
    }
    const uint8_t method = rbuf_[1];
    if (method == kAuthUserPass) {
      SendUpstreamAuth();
    } else if (method == kAuthNone) {
      // Proxy accepts unauthenticated; skip RFC 1929 and send the request.
      SendUpstreamRequest();
    } else {
      Fail();
    }
  }

  void SendUpstreamAuth() {
    std::vector<uint8_t> auth;
    auth.push_back(kRfc1929Version);
    auth.push_back(static_cast<uint8_t>(proxy_.username.size()));
    auth.insert(auth.end(), proxy_.username.begin(), proxy_.username.end());
    auth.push_back(static_cast<uint8_t>(proxy_.password.size()));
    auth.insert(auth.end(), proxy_.password.begin(), proxy_.password.end());
    WriteAll(upstream_.get(), std::move(auth),
             base::BindOnce(&BridgeConnection::OnUpstreamAuthSent,
                            base::Unretained(this)));
  }

  void OnUpstreamAuthSent() {
    ReadN(upstream_.get(), 2,
          base::BindOnce(&BridgeConnection::OnUpstreamAuthReply,
                         base::Unretained(this)));
  }

  void OnUpstreamAuthReply() {
    // RFC 1929: VER, STATUS (0 == success).
    if (rbuf_[1] != 0x00) {
      VLOG(1) << "Monti SOCKS bridge: upstream auth rejected.";
      Fail();
      return;
    }
    SendUpstreamRequest();
  }

  void SendUpstreamRequest() {
    WriteAll(upstream_.get(), request_,
             base::BindOnce(&BridgeConnection::OnUpstreamRequestSent,
                            base::Unretained(this)));
  }

  void OnUpstreamRequestSent() {
    ReadN(upstream_.get(), 4,
          base::BindOnce(&BridgeConnection::OnUpstreamReplyHeader,
                         base::Unretained(this)));
  }

  void OnUpstreamReplyHeader() {
    reply_.assign(rbuf_.begin(), rbuf_.end());
    const uint8_t atyp = rbuf_[3];
    if (atyp == kAtypIPv4) {
      ReadN(upstream_.get(), 4 + 2,
            base::BindOnce(&BridgeConnection::OnUpstreamReplyAddr,
                           base::Unretained(this)));
    } else if (atyp == kAtypIPv6) {
      ReadN(upstream_.get(), 16 + 2,
            base::BindOnce(&BridgeConnection::OnUpstreamReplyAddr,
                           base::Unretained(this)));
    } else if (atyp == kAtypDomain) {
      ReadN(upstream_.get(), 1,
            base::BindOnce(&BridgeConnection::OnUpstreamReplyDomainLen,
                           base::Unretained(this)));
    } else {
      Fail();
    }
  }

  void OnUpstreamReplyDomainLen() {
    reply_.push_back(rbuf_[0]);
    const size_t domain_len = rbuf_[0];
    ReadN(upstream_.get(), domain_len + 2,
          base::BindOnce(&BridgeConnection::OnUpstreamReplyAddr,
                         base::Unretained(this)));
  }

  void OnUpstreamReplyAddr() {
    reply_.insert(reply_.end(), rbuf_.begin(), rbuf_.end());
    // Forward the upstream's CONNECT reply back to the local client.
    WriteAll(local_.get(), reply_,
             base::BindOnce(&BridgeConnection::OnLocalReplySent,
                            base::Unretained(this)));
  }

  void OnLocalReplySent() { StartRelay(); }

  // --- Transparent bidirectional relay ----------------------------------

  void StartRelay() {
    RelayStart(local_.get(), upstream_.get());
    RelayStart(upstream_.get(), local_.get());
  }

  void RelayStart(net::StreamSocket* src, net::StreamSocket* dest) {
    auto buf = base::MakeRefCounted<net::GrowableIOBuffer>();
    buf->SetCapacity(kRelayCapacity);
    RelayRead(src, dest, std::move(buf));
  }

  void RelayRead(net::StreamSocket* src,
                 net::StreamSocket* dest,
                 scoped_refptr<net::GrowableIOBuffer> buf) {
    int rv = src->Read(buf.get(), buf->size(),
                       base::BindOnce(&BridgeConnection::OnRelayRead,
                                      base::Unretained(this), src, dest, buf));
    if (rv != net::ERR_IO_PENDING) {
      OnRelayRead(src, dest, std::move(buf), rv);
    }
  }

  void OnRelayRead(net::StreamSocket* src,
                   net::StreamSocket* dest,
                   scoped_refptr<net::GrowableIOBuffer> buf,
                   int rv) {
    if (rv <= 0) {
      Fail();
      return;
    }
    RelayWrite(src, dest, std::move(buf), rv);
  }

  void RelayWrite(net::StreamSocket* src,
                  net::StreamSocket* dest,
                  scoped_refptr<net::GrowableIOBuffer> buf,
                  int remaining) {
    int rv = dest->Write(
        buf.get(), remaining,
        base::BindOnce(&BridgeConnection::OnRelayWrite, base::Unretained(this),
                       src, dest, buf, remaining),
        kTrafficAnnotation);
    if (rv != net::ERR_IO_PENDING) {
      OnRelayWrite(src, dest, std::move(buf), remaining, rv);
    }
  }

  void OnRelayWrite(net::StreamSocket* src,
                    net::StreamSocket* dest,
                    scoped_refptr<net::GrowableIOBuffer> buf,
                    int remaining,
                    int rv) {
    if (rv < 0) {
      Fail();
      return;
    }
    buf->DidConsume(rv);
    remaining -= rv;
    if (remaining > 0) {
      RelayWrite(src, dest, std::move(buf), remaining);
      return;
    }
    buf->set_offset(0);
    RelayRead(src, dest, std::move(buf));
  }

  // Tears down this connection. Idempotent; safe to call from inside a socket
  // completion callback (destruction is deferred off the current call stack).
  void Fail();

  // Runs on a fresh task scheduled by Fail(); asks the owner to delete us.
  void DestroySelf();

  // Set once Fail() has scheduled teardown, so the second relay direction's
  // callback (or any re-entrant failure) doesn't schedule it again.
  bool failed_ = false;

  raw_ptr<BridgeInstance> owner_;
  const MontiProxy proxy_;
  std::unique_ptr<net::StreamSocket> local_;
  std::unique_ptr<net::TCPClientSocket> upstream_;

  scoped_refptr<net::IOBufferWithSize> scratch_;
  std::vector<uint8_t> rbuf_;
  size_t rbuf_need_ = 0;
  raw_ptr<net::StreamSocket> read_socket_ = nullptr;
  base::OnceClosure read_done_;

  scoped_refptr<net::DrainableIOBuffer> write_drain_;
  raw_ptr<net::StreamSocket> write_socket_ = nullptr;
  base::OnceClosure write_done_;

  std::vector<uint8_t> request_;  // client's SOCKS5 request, replayed upstream
  std::vector<uint8_t> reply_;    // upstream's reply, forwarded to the client
  std::string target_host_;
  uint16_t target_port_ = 0;
  std::string http_response_;
  bool force_socks_upstream_ = false;

  base::WeakPtrFactory<BridgeConnection> weak_factory_{this};
};

// One listener per upstream proxy. Owns its accepted connections.
class SocksBridge::BridgeInstance {
 public:
  explicit BridgeInstance(MontiProxy proxy) : proxy_(std::move(proxy)) {}

  BridgeInstance(const BridgeInstance&) = delete;
  BridgeInstance& operator=(const BridgeInstance&) = delete;
  ~BridgeInstance() = default;

  const std::string& proxy_id() const { return proxy_.id; }
  int port() const { return port_; }

  // Binds a listener on 127.0.0.1:<ephemeral>. Returns the port, or 0 on error.
  int Listen() {
    server_ = std::make_unique<net::TCPServerSocket>(net::NetLog::Get(),
                                                     net::NetLogSource());
    int rv = server_->Listen(
        net::IPEndPoint(net::IPAddress::IPv4Localhost(), 0), /*backlog=*/5,
        /*ipv6_only=*/std::nullopt);
    if (rv != net::OK) {
      return 0;
    }
    net::IPEndPoint local;
    if (server_->GetLocalAddress(&local) != net::OK) {
      return 0;
    }
    port_ = local.port();
    return port_;
  }

  void StartAcceptLoop() { DoAccept(); }

  void RemoveConnection(BridgeConnection* conn) {
    auto it = connections_.find(conn);
    if (it != connections_.end()) {
      connections_.erase(it);
    }
  }

 private:
  void DoAccept() {
    while (true) {
      int rv = server_->Accept(
          &accepted_, base::BindOnce(&BridgeInstance::OnAccept,
                                     base::Unretained(this)));
      if (rv == net::ERR_IO_PENDING) {
        return;
      }
      if (!HandleAccept(rv)) {
        return;
      }
    }
  }

  void OnAccept(int rv) {
    if (HandleAccept(rv)) {
      DoAccept();
    }
  }

  // Returns true to keep accepting, false to stop (fatal listener error).
  bool HandleAccept(int rv) {
    if (rv != net::OK) {
      // A transient per-connection error is fine to skip; treat anything here
      // conservatively by continuing to accept.
      return rv != net::ERR_UNEXPECTED;
    }
    auto conn = std::make_unique<BridgeConnection>(this, std::move(accepted_),
                                                   proxy_);
    BridgeConnection* raw = conn.get();
    connections_.insert(std::move(conn));
    raw->Start();
    return true;
  }

  MontiProxy proxy_;
  std::unique_ptr<net::TCPServerSocket> server_;
  std::unique_ptr<net::StreamSocket> accepted_;
  std::set<std::unique_ptr<BridgeConnection>, base::UniquePtrComparator>
      connections_;
  int port_ = 0;
};

void SocksBridge::BridgeConnection::Fail() {
  // This is reached from inside a socket completion callback (handshake reads/
  // writes or either relay direction). Destroying `this` here would also destroy
  // the very `net::TCPClientSocket`/`StreamSocket` whose callback is currently on
  // the stack, which is a use-after-free in the net message pump. Instead, defer
  // the teardown to a fresh task on this sequence so it runs only after we have
  // unwound out of the socket callback. The guard makes this idempotent: the
  // other relay direction's later callback will call Fail() again and no-op.
  if (failed_) {
    return;
  }
  failed_ = true;
  // Route through a WeakPtr to ourselves: if teardown (e.g. StopBridge) destroys
  // this connection before the task runs, the task is cancelled rather than
  // touching a freed `owner_`/`this`.
  base::SequencedTaskRunner::GetCurrentDefault()->PostTask(
      FROM_HERE, base::BindOnce(&BridgeConnection::DestroySelf,
                                weak_factory_.GetWeakPtr()));
}

void SocksBridge::BridgeConnection::DestroySelf() {
  // `owner_` is necessarily alive here: it owns this connection, so if it had
  // been destroyed this WeakPtr-bound task would not have run.
  owner_->RemoveConnection(this);
}

// --- SocksBridge ------------------------------------------------------------

// static
SocksBridge* SocksBridge::GetInstance() {
  static base::NoDestructor<SocksBridge> instance;
  return instance.get();
}

SocksBridge::SocksBridge() : io_thread_("MontiSocksBridge") {
  base::Thread::Options options(base::MessagePumpType::IO, 0);
  io_thread_.StartWithOptions(std::move(options));
}

SocksBridge::~SocksBridge() = default;

void SocksBridge::StartBridge(const MontiProxy& proxy,
                              base::OnceCallback<void(int)> callback) {
  io_thread_.task_runner()->PostTask(
      FROM_HERE,
      base::BindOnce(&SocksBridge::StartOnIo, base::Unretained(this), proxy,
                     base::SequencedTaskRunner::GetCurrentDefault(),
                     std::move(callback)));
}

void SocksBridge::StopBridge(const std::string& proxy_id) {
  io_thread_.task_runner()->PostTask(
      FROM_HERE, base::BindOnce(&SocksBridge::StopOnIo, base::Unretained(this),
                                proxy_id));
}

void SocksBridge::StartOnIo(
    MontiProxy proxy,
    scoped_refptr<base::SequencedTaskRunner> reply_runner,
    base::OnceCallback<void(int)> callback) {
  auto it = instances_.find(proxy.id);
  if (it != instances_.end()) {
    reply_runner->PostTask(
        FROM_HERE, base::BindOnce(std::move(callback), it->second->port()));
    return;
  }

  auto instance = std::make_unique<BridgeInstance>(std::move(proxy));
  int port = instance->Listen();
  if (port <= 0) {
    reply_runner->PostTask(FROM_HERE, base::BindOnce(std::move(callback), 0));
    return;
  }
  instance->StartAcceptLoop();
  const std::string id = instance->proxy_id();
  instances_[id] = std::move(instance);
  reply_runner->PostTask(FROM_HERE, base::BindOnce(std::move(callback), port));
}

void SocksBridge::StopOnIo(std::string proxy_id) {
  instances_.erase(proxy_id);
}

}  // namespace monti
